#' \describe{
#'   \item{neighborho}{NA}
#'   \item{name}{NA}
#'   \item{sup_km2}{NA}
#'   \item{sector_id}{NA}
#'   \item{cte}{NA}
#'   \item{qlty_water}{NA}
#'   \item{qty_water}{NA}
#'   \item{health_car}{NA}
#'   \item{schooling}{NA}
#'   \item{transport}{NA}
#'   \item{economy}{NA}
#'   \item{ranking}{NA}
#'   \item{sup_bati}{NA}
#'   \item{density}{NA}
#'   \item{aptitude}{NA}
#'   \item{zoning}{NA}
#'   \item{latrine}{NA}
#'   \item{standing}{NA}
#'   \item{density_ra}{NA}
#'   \item{economy_nu}{NA}
#'   \item{geometry}{NA}
#'   \item{Latitude.o}{NA}
#'   \item{Longitude}{NA}
#'   \item{Administra}{NA}
#'   \item{Type}{NA}
#'   \item{Date.added}{NA}
#'   \item{Datasets..}{NA}
#'   \item{geometry}{NA}
#' }
